[project]
name = 'Heritage-Grain-Production'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.growing-protocol]
path = 'contracts/growing-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.seed-purity-verification]
path = 'contracts/seed-purity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.variety-registration]
path = 'contracts/variety-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
